num_epochs: 30
lr: 0.001
batch_size: 128 #64 #32 #256
image_size: 224
fc1_size: 512
basic: False
cropping: False
augmentations: True
albumentations: False
balance: True
scheduler: ""
model: "cnn"
use_best_checkpoint: False